# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qz3e_lB80ckckmAf91ZBmJlp5-rIbgLc
"""

import requests
import pandas as pd
from sqlalchemy import create_engine

def run_crypto_pipeline():
    try:
        print("⏳ 1. Extraction Started...")
        url = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1"
        response = requests.get(url)
        df_raw = pd.DataFrame(response.json())

        print("⏳ 2. Transformation Started...")
        df_clean = df_raw[['name', 'current_price', 'market_cap']]
        df_transformed = df_clean.rename(columns={
            'name': 'Crypto_Name',
            'current_price': 'Price_USD',
            'market_cap': 'Market_Cap_USD'
        })
        df_transformed['Price_EGP'] = df_transformed['Price_USD'] * 48

        print("⏳ 3. Loading Data to Cloud PostgreSQL...")
        db_url = "postgresql://postgres.wuxplugsmvqdsmjmofrz:AhmedMekky2026@aws-0-eu-west-1.pooler.supabase.com:5432/postgres"
        engine = create_engine(db_url)
        df_transformed.to_sql('crypto_live_table', con=engine, if_exists='replace', index=False)

        print("🎯 Success! Data updated in Supabase.")
    except Exception as e:
        print(f"❌ Error occurred: {e}")

if __name__ == "__main__":
    run_crypto_pipeline()